-- One membership, three durations — 2026-07-26.
-- Replaces the Core/Private tier split. Access was never actually gated per
-- tier (no min_tier anywhere); the two tiers only differed in price and copy.
-- So `tier` becomes a binary access flag and the duration moves to `plan`.
-- Run once in the Supabase SQL editor. Safe to re-run.
--
-- ORDER MATTERS: schema.sql declares
--   profiles.tier  check (tier in ('none','core','private'))
--   applications.requested_tier check (requested_tier in ('core','private'))
-- so the old constraints must be dropped BEFORE the data is migrated to
-- 'member', or every UPDATE below fails with a check violation.

begin;

-- 0. PREREQUISITES.
--    The live database turned out to be missing 20260708_applications_payment
--    (and possibly parts of 20260712_subscriptions), so `granted_tier` did not
--    exist and this migration failed on first run. Rather than depend on those
--    having been applied, ensure every column we touch exists. All of these are
--    ADD COLUMN IF NOT EXISTS, so this is a no-op on an up-to-date database and
--    leaves the schema identical either way.
--    granted_tier is added WITHOUT the old core/private check — step 3 installs
--    the correct constraint for the new model.
alter table public.applications
  add column if not exists requested_tier text,
  add column if not exists granted_tier text,
  add column if not exists stripe_session_id text,
  add column if not exists paid_at timestamptz,
  add column if not exists stripe_customer_id text,
  add column if not exists stripe_subscription_id text;

alter table public.profiles
  add column if not exists stripe_customer_id text,
  add column if not exists stripe_subscription_id text,
  add column if not exists subscription_status text,
  add column if not exists current_period_end timestamptz;

create index if not exists profiles_stripe_customer_idx
  on public.profiles (stripe_customer_id);

-- Payment state is webhook-only (service_role bypasses this).
revoke update (stripe_customer_id, stripe_subscription_id,
               subscription_status, current_period_end)
  on public.profiles from authenticated, anon;

-- 1. Drop the existing check constraints on the three tier columns. The names
--    are generated by Postgres, so find them rather than guessing: an inline
--    `check` in a create table may not be named exactly <table>_<col>_check.
do $$
declare
  c record;
begin
  for c in
    select rel.relname as table_name, con.conname as constraint_name
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and con.contype = 'c'
      and (
        (rel.relname = 'profiles'
          and pg_get_constraintdef(con.oid) ilike '%tier%')
        or (rel.relname = 'applications'
          and pg_get_constraintdef(con.oid) ilike '%tier%')
      )
  loop
    execute format('alter table public.%I drop constraint %I',
                   c.table_name, c.constraint_name);
  end loop;
end $$;

-- 2. Existing paying members must NOT lose access: both old tiers map to the
--    single 'member' tier.
update public.profiles
  set tier = 'member'
  where tier in ('core', 'private');

update public.applications
  set granted_tier = 'member'
  where granted_tier in ('core', 'private');

update public.applications
  set requested_tier = 'member'
  where requested_tier in ('core', 'private');

-- 3. Re-add the constraints, now matching the new model.
alter table public.profiles
  add constraint profiles_tier_check
  check (tier in ('none', 'member'));

alter table public.applications
  add constraint applications_granted_tier_check
  check (granted_tier is null or granted_tier = 'member');

alter table public.applications
  add constraint applications_requested_tier_check
  check (requested_tier is null or requested_tier = 'member');

-- 4. Which duration the member bought. Informational only — it drives the
--    renewal price and what we show on the profile, never the access check.
do $$ begin
  create type public.membership_plan as enum ('3m', '6m', '1y');
exception
  when duplicate_object then null;
end $$;

alter table public.profiles
  add column if not exists plan public.membership_plan;

alter table public.applications
  add column if not exists requested_plan public.membership_plan,
  add column if not exists granted_plan public.membership_plan;

-- 5. Same lockdown as the other payment columns: `plan` is payment state, so
--    only the webhook (service_role) may write it.
revoke update (plan) on public.profiles from authenticated, anon;

commit;
